-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2021-12-23 14:07:10 CET
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE additional_notes (
    note_id         INTEGER NOT NULL,
    kanji_character VARCHAR2(3) NOT NULL,
    type            VARCHAR2(32) NOT NULL,
    note            VARCHAR2(1000) NOT NULL,
    date_added      DATE NOT NULL
);

ALTER TABLE additional_notes ADD CONSTRAINT additional_notes_pk PRIMARY KEY ( note_id );

CREATE TABLE kanji (
    character           VARCHAR2(3) NOT NULL,
    date_added          DATE NOT NULL,
    proficiency         INTEGER NOT NULL,
    last_tested         DATE NOT NULL,
    jlpt_classification INTEGER
);

ALTER TABLE kanji ADD CONSTRAINT kanji_pk PRIMARY KEY ( character );

CREATE TABLE meaning (
    meaning_id      INTEGER NOT NULL,
    meaning         VARCHAR2(512) NOT NULL,
    kanji_character VARCHAR2(3) NOT NULL
);

ALTER TABLE meaning ADD CONSTRAINT meaning_pk PRIMARY KEY ( meaning_id );

CREATE TABLE reading (
    reading_id      INTEGER NOT NULL,
    reading         VARCHAR2(50) NOT NULL,
    kanji_character VARCHAR2(3) NOT NULL
);

ALTER TABLE reading ADD CONSTRAINT reading_pk PRIMARY KEY ( reading_id );

CREATE TABLE usage (
    example_id      INTEGER NOT NULL,
    example         VARCHAR2(256) NOT NULL,
    kanji_character VARCHAR2(3) NOT NULL
);

ALTER TABLE usage ADD CONSTRAINT usage_pk PRIMARY KEY ( example_id );

ALTER TABLE additional_notes
    ADD CONSTRAINT additional_notes_kanji_fk FOREIGN KEY ( kanji_character )
        REFERENCES kanji ( character ) on delete cascade;

ALTER TABLE meaning
    ADD CONSTRAINT meaning_kanji_fk FOREIGN KEY ( kanji_character )
        REFERENCES kanji ( character ) on delete cascade;

ALTER TABLE reading
    ADD CONSTRAINT reading_kanji_fk FOREIGN KEY ( kanji_character )
        REFERENCES kanji ( character ) on delete cascade;

ALTER TABLE usage
    ADD CONSTRAINT usage_kanji_fk FOREIGN KEY ( kanji_character )
        REFERENCES kanji ( character ) on delete cascade;

CREATE SEQUENCE additional_notes_note_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER additional_notes_note_id_trg BEFORE
    INSERT ON additional_notes
    FOR EACH ROW
    WHEN ( new.note_id IS NULL )
BEGIN
    :new.note_id := additional_notes_note_id_seq.nextval;
END;
/

CREATE SEQUENCE meaning_meaning_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER meaning_meaning_id_trg BEFORE
    INSERT ON meaning
    FOR EACH ROW
    WHEN ( new.meaning_id IS NULL )
BEGIN
    :new.meaning_id := meaning_meaning_id_seq.nextval;
END;
/

CREATE SEQUENCE reading_reading_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER reading_reading_id_trg BEFORE
    INSERT ON reading
    FOR EACH ROW
    WHEN ( new.reading_id IS NULL )
BEGIN
    :new.reading_id := reading_reading_id_seq.nextval;
END;
/

CREATE SEQUENCE usage_example_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER usage_example_id_trg BEFORE
    INSERT ON usage
    FOR EACH ROW
    WHEN ( new.example_id IS NULL )
BEGIN
    :new.example_id := usage_example_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           4
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          4
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
